[workspace]
members = ["engine", "game", "standalone"]
default-members = ["standalone"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
dll_patch = { path = "../dll_live_patching/dll_patch" }

[profile.dev]
debug = true
opt-level = 0

[profile.release]
debug = false
opt-level = 2
