#!/usr/bin/env python3
"""
gen_bloat.py — Generate game/src/bloat.rs to inflate compile time.

Each function contains format!() calls, string ops, and branching —
enough unique work per function that the Rust compiler cannot fully
deduplicate the effort across thousands of copies.

USAGE
    python gen_bloat.py              # uses default count (5000)
    python gen_bloat.py 2000         # 2000 functions (~5s build)
    python gen_bloat.py 10000        # 10000 functions (~25s build)
    python gen_bloat.py 5000 --run   # generate AND build + run standalone
"""

import sys
import subprocess
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent
OUTPUT_FILE = WORKSPACE_ROOT / "game" / "src" / "bloat_gen.rs"
DEFAULT_COUNT = 5000


def generate_bloat(function_count: int) -> None:
    """Write bloat.rs with `function_count` unique extern "C" functions."""
    print(f"[gen_bloat] generating {function_count} functions → {OUTPUT_FILE}")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as file:
        file.write("// auto-generated by gen_bloat.py — do not edit by hand\n")
        file.write(f"// {function_count} unique functions with format! calls\n")
        file.write("\n")

        for index in range(function_count):
            file.write("#[unsafe(no_mangle)]\n")
            file.write(f"pub extern \"C\" fn bloat_{index}() -> i32 {{\n")
            file.write(f"    let _name = format!(\"bloat_function_number_{index}\");\n")
            file.write(f"    let _greeting = format!(\"hello from bloat #{index}: {{}}\", _name);\n")
            file.write( "    let _upper = _greeting.to_uppercase();\n")
            file.write( "    let _len = _upper.len();\n")
            if index % 2 == 0:
                file.write(f"    let _extra = format!(\"even seed: {{}}\", {index});\n")
                file.write( "    (_len + _extra.len()) as i32\n")
            else:
                file.write(f"    let _extra = format!(\"odd seed: {{}}\", {index});\n")
                file.write( "    (_len + _extra.len() + 1) as i32\n")
            file.write("}\n")
            file.write("\n")

    size_kb = OUTPUT_FILE.stat().st_size / 1024
    print(f"[gen_bloat] done — {size_kb:.0f} KB written")


def main() -> None:
    function_count = DEFAULT_COUNT
    run_after = False

    for argument in sys.argv[1:]:
        if argument == "--run":
            run_after = True
        else:
            try:
                function_count = int(argument)
            except ValueError:
                print(f"ignoring unknown argument: {argument}", file=sys.stderr)

    generate_bloat(function_count)

    if run_after:
        print("[gen_bloat] building game DLL...")
        subprocess.run(
            ["cargo", "build", "-p", "game"],
            cwd=str(WORKSPACE_ROOT),
            check=False,
        )
        print("[gen_bloat] launching standalone...")
        subprocess.run(
            ["cargo", "run", "-p", "standalone"],
            cwd=str(WORKSPACE_ROOT),
            check=False,
        )


if __name__ == "__main__":
    main()
