// modules — auto-generated by generate_modules.py, do not edit by hand.
// Root of the interconnected module graph.  `run_update` and `run_compute`
// fan out into all 50 submodules, making every function in the
// graph reachable from the DLL's exported entry points.

pub mod module_000;
pub mod module_001;
pub mod module_002;
pub mod module_003;
pub mod module_004;
pub mod module_005;
pub mod module_006;
pub mod module_007;
pub mod module_008;
pub mod module_009;
pub mod module_010;
pub mod module_011;
pub mod module_012;
pub mod module_013;
pub mod module_014;
pub mod module_015;
pub mod module_016;
pub mod module_017;
pub mod module_018;
pub mod module_019;
pub mod module_020;
pub mod module_021;
pub mod module_022;
pub mod module_023;
pub mod module_024;
pub mod module_025;
pub mod module_026;
pub mod module_027;
pub mod module_028;
pub mod module_029;
pub mod module_030;
pub mod module_031;
pub mod module_032;
pub mod module_033;
pub mod module_034;
pub mod module_035;
pub mod module_036;
pub mod module_037;
pub mod module_038;
pub mod module_039;
pub mod module_040;
pub mod module_041;
pub mod module_042;
pub mod module_043;
pub mod module_044;
pub mod module_045;
pub mod module_046;
pub mod module_047;
pub mod module_048;
pub mod module_049;

/// Fan out a game tick into every module and fold the results together.
/// Called by the exported `update` function in lib.rs.
pub fn run_update(input: i32) -> i32 {
    let part_000 = module_000::tick_000(input + 0);
    let part_001 = module_001::tick_001(input + 1);
    let part_002 = module_002::tick_002(input + 2);
    let part_003 = module_003::tick_003(input + 3);
    let part_004 = module_004::tick_004(input + 4);
    let part_005 = module_005::tick_005(input + 5);
    let part_006 = module_006::tick_006(input + 6);
    let part_007 = module_007::tick_007(input + 7);
    let part_008 = module_008::tick_008(input + 8);
    let part_009 = module_009::tick_009(input + 9);
    let part_010 = module_010::tick_010(input + 10);
    let part_011 = module_011::tick_011(input + 11);
    let part_012 = module_012::tick_012(input + 12);
    let part_013 = module_013::tick_013(input + 13);
    let part_014 = module_014::tick_014(input + 14);
    let part_015 = module_015::tick_015(input + 15);
    let part_016 = module_016::tick_016(input + 16);
    let part_017 = module_017::tick_017(input + 17);
    let part_018 = module_018::tick_018(input + 18);
    let part_019 = module_019::tick_019(input + 19);
    let part_020 = module_020::tick_020(input + 20);
    let part_021 = module_021::tick_021(input + 21);
    let part_022 = module_022::tick_022(input + 22);
    let part_023 = module_023::tick_023(input + 23);
    let part_024 = module_024::tick_024(input + 24);
    let part_025 = module_025::tick_025(input + 25);
    let part_026 = module_026::tick_026(input + 26);
    let part_027 = module_027::tick_027(input + 27);
    let part_028 = module_028::tick_028(input + 28);
    let part_029 = module_029::tick_029(input + 29);
    let part_030 = module_030::tick_030(input + 30);
    let part_031 = module_031::tick_031(input + 31);
    let part_032 = module_032::tick_032(input + 32);
    let part_033 = module_033::tick_033(input + 33);
    let part_034 = module_034::tick_034(input + 34);
    let part_035 = module_035::tick_035(input + 35);
    let part_036 = module_036::tick_036(input + 36);
    let part_037 = module_037::tick_037(input + 37);
    let part_038 = module_038::tick_038(input + 38);
    let part_039 = module_039::tick_039(input + 39);
    let part_040 = module_040::tick_040(input + 40);
    let part_041 = module_041::tick_041(input + 41);
    let part_042 = module_042::tick_042(input + 42);
    let part_043 = module_043::tick_043(input + 43);
    let part_044 = module_044::tick_044(input + 44);
    let part_045 = module_045::tick_045(input + 45);
    let part_046 = module_046::tick_046(input + 46);
    let part_047 = module_047::tick_047(input + 47);
    let part_048 = module_048::tick_048(input + 48);
    let part_049 = module_049::tick_049(input + 49);
    (part_000 + part_001 + part_002 + part_003 + part_004 + part_005 + part_006 + part_007 + part_008 + part_009 + part_010 + part_011 + part_012 + part_013 + part_014 + part_015 + part_016 + part_017 + part_018 + part_019 + part_020 + part_021 + part_022 + part_023 + part_024 + part_025 + part_026 + part_027 + part_028 + part_029 + part_030 + part_031 + part_032 + part_033 + part_034 + part_035 + part_036 + part_037 + part_038 + part_039 + part_040 + part_041 + part_042 + part_043 + part_044 + part_045 + part_046 + part_047 + part_048 + part_049) % 100000
}

/// Fan out a compute request into every module and fold the results.
/// Called by the exported `compute` function in lib.rs.
pub fn run_compute(x: i32, y: i32) -> i32 {
    let part_000 = module_000::compute_000(x + 0, y + 0);
    let part_001 = module_001::compute_001(x + 1, y + 2);
    let part_002 = module_002::compute_002(x + 2, y + 4);
    let part_003 = module_003::compute_003(x + 3, y + 6);
    let part_004 = module_004::compute_004(x + 4, y + 8);
    let part_005 = module_005::compute_005(x + 5, y + 10);
    let part_006 = module_006::compute_006(x + 6, y + 12);
    let part_007 = module_007::compute_007(x + 7, y + 14);
    let part_008 = module_008::compute_008(x + 8, y + 16);
    let part_009 = module_009::compute_009(x + 9, y + 18);
    let part_010 = module_010::compute_010(x + 10, y + 20);
    let part_011 = module_011::compute_011(x + 11, y + 22);
    let part_012 = module_012::compute_012(x + 12, y + 24);
    let part_013 = module_013::compute_013(x + 13, y + 26);
    let part_014 = module_014::compute_014(x + 14, y + 28);
    let part_015 = module_015::compute_015(x + 15, y + 30);
    let part_016 = module_016::compute_016(x + 16, y + 32);
    let part_017 = module_017::compute_017(x + 17, y + 34);
    let part_018 = module_018::compute_018(x + 18, y + 36);
    let part_019 = module_019::compute_019(x + 19, y + 38);
    let part_020 = module_020::compute_020(x + 20, y + 40);
    let part_021 = module_021::compute_021(x + 21, y + 42);
    let part_022 = module_022::compute_022(x + 22, y + 44);
    let part_023 = module_023::compute_023(x + 23, y + 46);
    let part_024 = module_024::compute_024(x + 24, y + 48);
    let part_025 = module_025::compute_025(x + 25, y + 50);
    let part_026 = module_026::compute_026(x + 26, y + 52);
    let part_027 = module_027::compute_027(x + 27, y + 54);
    let part_028 = module_028::compute_028(x + 28, y + 56);
    let part_029 = module_029::compute_029(x + 29, y + 58);
    let part_030 = module_030::compute_030(x + 30, y + 60);
    let part_031 = module_031::compute_031(x + 31, y + 62);
    let part_032 = module_032::compute_032(x + 32, y + 64);
    let part_033 = module_033::compute_033(x + 33, y + 66);
    let part_034 = module_034::compute_034(x + 34, y + 68);
    let part_035 = module_035::compute_035(x + 35, y + 70);
    let part_036 = module_036::compute_036(x + 36, y + 72);
    let part_037 = module_037::compute_037(x + 37, y + 74);
    let part_038 = module_038::compute_038(x + 38, y + 76);
    let part_039 = module_039::compute_039(x + 39, y + 78);
    let part_040 = module_040::compute_040(x + 40, y + 80);
    let part_041 = module_041::compute_041(x + 41, y + 82);
    let part_042 = module_042::compute_042(x + 42, y + 84);
    let part_043 = module_043::compute_043(x + 43, y + 86);
    let part_044 = module_044::compute_044(x + 44, y + 88);
    let part_045 = module_045::compute_045(x + 45, y + 90);
    let part_046 = module_046::compute_046(x + 46, y + 92);
    let part_047 = module_047::compute_047(x + 47, y + 94);
    let part_048 = module_048::compute_048(x + 48, y + 96);
    let part_049 = module_049::compute_049(x + 49, y + 98);
    (part_000 + part_001 + part_002 + part_003 + part_004 + part_005 + part_006 + part_007 + part_008 + part_009 + part_010 + part_011 + part_012 + part_013 + part_014 + part_015 + part_016 + part_017 + part_018 + part_019 + part_020 + part_021 + part_022 + part_023 + part_024 + part_025 + part_026 + part_027 + part_028 + part_029 + part_030 + part_031 + part_032 + part_033 + part_034 + part_035 + part_036 + part_037 + part_038 + part_039 + part_040 + part_041 + part_042 + part_043 + part_044 + part_045 + part_046 + part_047 + part_048 + part_049) % 100000
}
