#!/usr/bin/env python3
"""Build the AAA scenario module tree generated by generate_aaa_modules.py.

Builds core -> subsystem -> leaf, IN THAT ORDER, all sharing one
--target-dir. Order matters: each tier's crates link against the previous
tiers' .dll.lib import libraries at build time (see the generated build.rs
in any subsystem/leaf crate) — Cargo's own dependency graph has no idea about
that link, since it happens via linker args rather than a `[dependencies]`
entry, so nothing else enforces the ordering.

Usage:
    python build_aaa_scenario.py                 # generate (if missing) + build all tiers, release
    python build_aaa_scenario.py --regen --scale medium
    python build_aaa_scenario.py --tier leaf      # rebuild just one tier (others must exist already)
"""

import argparse
import os
import subprocess
import sys
import time

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "aaa_scenario")
TIERS = ["core", "subsystem", "leaf"]


def run_cargo_build(tier_dir, target_dir, jobs=None):
    manifest = os.path.join(tier_dir, "Cargo.toml")
    cmd = ["cargo", "build", "--release",
           "--manifest-path", manifest,
           "--target-dir", target_dir]
    if jobs:
        cmd += ["-j", str(jobs)]
    print(f"$ {' '.join(cmd)}")
    start = time.time()
    result = subprocess.run(cmd)
    elapsed = time.time() - start
    if result.returncode != 0:
        print(f"FAILED (exit {result.returncode}) after {elapsed:.1f}s", file=sys.stderr)
        sys.exit(result.returncode)
    print(f"OK ({elapsed:.1f}s)")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--regen", action="store_true", help="Re-run generate_aaa_modules.py first")
    parser.add_argument("--scale", choices=["small", "medium", "full"], default="full",
                         help="Passed through to generate_aaa_modules.py when --regen is set")
    parser.add_argument("--tier", choices=TIERS, default=None,
                         help="Build only this tier (earlier tiers must already be built)")
    parser.add_argument("--jobs", type=int, default=None, help="Passed to cargo build -j")
    args = parser.parse_args()

    if args.regen or not os.path.isdir(OUT_DIR):
        gen_cmd = [sys.executable, os.path.join(SCRIPT_DIR, "generate_aaa_modules.py"),
                   "--scale", args.scale, "--clean"]
        print(f"$ {' '.join(gen_cmd)}")
        subprocess.run(gen_cmd, check=True)

    target_dir = os.path.join(OUT_DIR, "target")
    tiers_to_build = [args.tier] if args.tier else TIERS

    overall_start = time.time()
    for tier in tiers_to_build:
        tier_dir = os.path.join(OUT_DIR, tier)
        if not os.path.isdir(tier_dir):
            print(f"error: {tier_dir} does not exist — generate the scenario first", file=sys.stderr)
            sys.exit(1)
        print(f"\n=== Building tier: {tier} ===")
        run_cargo_build(tier_dir, target_dir, jobs=args.jobs)

    print(f"\nAll requested tiers built in {time.time() - overall_start:.1f}s total.")
    print(f"Shared output dir: {os.path.join(target_dir, 'release')}")
    print("\nNext: cargo run -p stress_test --release")


if __name__ == "__main__":
    main()
