// build.rs — Generates bloat.rs at compile time with uniquely-named
// functions that each contain a format! call (expensive to compile).

use std::io::Write;

fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let destination = std::path::Path::new(&out_dir).join("bloat.rs");
    let mut file = std::fs::File::create(&destination).unwrap();

    let function_count: usize = std::env::var("BLOAT_COUNT")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(5000);

    writeln!(file, "// auto-generated by build.rs — do not edit").unwrap();
    writeln!(
        file,
        "// {} unique functions with format! calls to inflate compile time",
        function_count
    )
    .unwrap();
    writeln!(file).unwrap();

    for index in 0..function_count {
        writeln!(file, "#[unsafe(no_mangle)]").unwrap();
        writeln!(file, "pub extern \"C\" fn bloat_{index}() -> i32 {{").unwrap();
        // Unique work per function: format string parsing, string ops,
        // branching on the index to prevent the compiler from deduplicating.
        writeln!(
            file,
            "    let _name = format!(\"bloat_function_number_{index}\");"
        )
        .unwrap();
        writeln!(
            file,
            "    let _greeting = format!(\"hello from bloat #{index}: {{}}\", _name);"
        )
        .unwrap();
        writeln!(file, "    let _upper = _greeting.to_uppercase();").unwrap();
        writeln!(file, "    let _len = _upper.len();").unwrap();
        writeln!(file, "    if {index} % 2 == 0 {{").unwrap();
        writeln!(
            file,
            "        let _extra = format!(\"even seed: {{}}\", {index});"
        )
        .unwrap();
        writeln!(file, "        (_len + _extra.len()) as i32").unwrap();
        writeln!(file, "    }} else {{").unwrap();
        writeln!(
            file,
            "        let _extra = format!(\"odd seed: {{}}\", {index});"
        )
        .unwrap();
        writeln!(file, "        (_len + _extra.len() + 1) as i32").unwrap();
        writeln!(file, "    }}").unwrap();
        writeln!(file, "}}").unwrap();
        writeln!(file).unwrap();
    }

    println!("cargo:rerun-if-env-changed=BLOAT_COUNT");
}
