//! # live_coding
//!
//! A reusable, engine-agnostic Live Coding system for Rust **cdylib**
//! projects (Windows x86/x64).
//!
//! The idea (Live++ / Unreal-style prologue patching):
//!
//! - A `project` crate is built once as a cdylib and loaded into the host
//!   process.  Every hot function's address is resolved through a single
//!   exported resolver entry point (the registry is auto-generated by the
//!   project's `build.rs` and keyed by fully-qualified path, so name
//!   collisions across scopes are impossible).
//! - When you edit a hot function's **body** and save, that one function is
//!   recompiled standalone with `rustc` (~200 ms) and its **prologue** (first
//!   5 bytes) in the loaded base DLL is overwritten with `E9 <rel32>` - a
//!   jump to the freshly compiled code.  The base DLL stays loaded and every
//!   existing caller keeps its pointer, so the running program is
//!   transparently redirected.  Far targets (> ±2 GB) go through a
//!   trampoline.
//! - Any other edit (consts, structs, plumbing, new functions, `Cargo.toml`)
//!   triggers a **full rebuild**: the fresh DLL is loaded alongside and the
//!   base prologue is re-patched to it (patches compose - each patched
//!   function calls back into the base, which is the single source of truth).
//!
//! # Threading contract
//!
//! All patching must happen on ONE thread (typically the render/main thread,
//! between frames), so no function is ever executing while its prologue bytes
//! are overwritten.  The [`LiveCodeSession`] is not `Sync`; keep it on one
//! thread.
//!
//! # Modules
//!
//! - [`analysis`] - a mini-lexer that extracts function bodies, private
//!   helpers, top-level consts/types/statics/imports/extern exports and
//!   strips hot bodies for change detection.
//! - [`symbols`] - the hot-symbol model (`HotSymbol`), source-file to
//!   module-scope mapping, qualified-path keys and the incremental
//!   [`symbols::SourceCache`].
//! - [`error`] - the unified [`error::LiveCodeError`] type.
//! - [`patch`] - the raw prologue-patching primitives plus `rustc`
//!   single-function compilation.
//! - [`module`] - generates the self-contained patch module source from the
//!   project's OWN definitions (real body + forwarding wrappers through a
//!   dependency-address table).
//! - [`session`] - [`LiveCodeSession`]: owns the loaded libraries, caches,
//!   change detection, per-function patching and full-reload fallback.
//!
//! # Example
//!
//! ```ignore
//! use live_coding::{LiveCodeSession, LiveCodeSessionConfig, ChangeOutcome};
//!
//! let workspace = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..");
//! let api_pointer: *const () = /* your project_set_api argument */;
//! let config = LiveCodeSessionConfig::mini_engine(&workspace, api_pointer);
//! let mut session = LiveCodeSession::new(config)?;   // validates the config
//!
//! let update_address = session.load_initial()?;      // point your engine here
//! // ... in your file-watcher callback:
//! match session.handle_change(&changed_paths)? {
//!     ChangeOutcome::FullReloadNeedsPointerSwap { update_address } => {
//!         // the base prologue could not be re-patched - swap the engine pointer
//!     }
//!     _ => {} // pointer unchanged
//! }
//! # Ok::<(), live_coding::error::LiveCodeError>(())
//! ```
//!
//! # The resolver pattern (project side)
//!
//! The project cdylib exports ONE resolver entry point backed by a
//! build-script-generated registry, so no function or module ever has to be
//! declared by hand.  A minimal generated registry looks like:
//!
//! ```text
//! "project_update" => project_update as *const () as usize,
//! "modules::run_update" => modules::run_update as *const () as usize,
//! "modules::module_003::scale_value_003" => modules::module_003::scale_value_003 as *const () as usize,
//! ```
//!
//! The exact entry-point names are configurable via
//! [`session::LiveCodingContract`] (defaults match the mini-engine layout).

#![warn(missing_docs)]
#![warn(clippy::undocumented_unsafe_blocks)]

pub mod analysis;
pub mod error;
pub mod module;
pub mod patch;
pub mod session;
pub mod style;
pub mod symbols;

pub use error::LiveCodeError;
pub use session::{ChangeOutcome, LiveCodeSession, LiveCodeSessionConfig, LiveCodingContract};
pub use symbols::HotSymbol;

/// How much the session logs (and whether output goes to stdout or to the
/// configured logger callback).  `Error` always reports (to stderr), even in
/// `Quiet` mode.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum LogLevel {
    /// Errors only (always printed, to stderr).
    Error,
    /// Suppress normal progress output.
    Quiet,
    /// The default: all normal progress output.
    Normal,
    /// Extra detail on top of [`LogLevel::Normal`].
    Verbose,
}

/// The hot-reloadable project's update entry point: `extern "C" fn(dt: f32)`.
pub type ProjectUpdateFn = extern "C" fn(delta_time: f32);
