// modules - auto-generated by generate_modules.py, do not edit by hand.
// Root of the interconnected module graph.  `run_update` and
// `run_compute` fan out into all submodules, making every function in
// the graph reachable from the DLL's exported entry points.

pub mod module_000;
pub mod module_001;
pub mod module_002;
pub mod module_003;
pub mod module_004;
pub mod module_005;
pub mod module_006;
pub mod module_007;
pub mod module_008;
pub mod module_009;
pub mod module_010;
pub mod module_011;
pub mod module_012;
pub mod module_013;
pub mod module_014;
pub mod module_015;
pub mod module_016;
pub mod module_017;
pub mod module_018;
pub mod module_019;

/// Fan out a game tick into every module and fold the results together.
/// Called by the exported `project_update` in lib.rs.
pub fn run_update(input: i32) -> i32 {
    let part_000 = module_000::tick_000(input + 0);
    let part_001 = module_001::tick_001(input + 1);
    let part_002 = module_002::tick_002(input + 2);
    let part_003 = module_003::tick_003(input + 3);
    let part_004 = module_004::tick_004(input + 4);
    let part_005 = module_005::tick_005(input + 5);
    let part_006 = module_006::tick_006(input + 6);
    let part_007 = module_007::tick_007(input + 7);
    let part_008 = module_008::tick_008(input + 8);
    let part_009 = module_009::tick_009(input + 9);
    let part_010 = module_010::tick_010(input + 10);
    let part_011 = module_011::tick_011(input + 11);
    let part_012 = module_012::tick_012(input + 12);
    let part_013 = module_013::tick_013(input + 13);
    let part_014 = module_014::tick_014(input + 14);
    let part_015 = module_015::tick_015(input + 15);
    let part_016 = module_016::tick_016(input + 16);
    let part_017 = module_017::tick_017(input + 17);
    let part_018 = module_018::tick_018(input + 18);
    let part_019 = module_019::tick_019(input + 19);
    (part_000
        + part_001
        + part_002
        + part_003
        + part_004
        + part_005
        + part_006
        + part_007
        + part_008
        + part_009
        + part_010
        + part_011
        + part_012
        + part_013
        + part_014
        + part_015
        + part_016
        + part_017
        + part_018
        + part_019)
        % 100000
}

/// Fan out a compute request into every module and fold the results.
/// Called by the exported `project_update` in lib.rs.
pub fn run_compute(x: i32, y: i32) -> i32 {
    let part_000 = module_000::compute_000(x + 0, y + 0);
    let part_001 = module_001::compute_001(x + 1, y + 2);
    let part_002 = module_002::compute_002(x + 2, y + 4);
    let part_003 = module_003::compute_003(x + 3, y + 6);
    let part_004 = module_004::compute_004(x + 4, y + 8);
    let part_005 = module_005::compute_005(x + 5, y + 10);
    let part_006 = module_006::compute_006(x + 6, y + 12);
    let part_007 = module_007::compute_007(x + 7, y + 14);
    let part_008 = module_008::compute_008(x + 8, y + 16);
    let part_009 = module_009::compute_009(x + 9, y + 18);
    let part_010 = module_010::compute_010(x + 10, y + 20);
    let part_011 = module_011::compute_011(x + 11, y + 22);
    let part_012 = module_012::compute_012(x + 12, y + 24);
    let part_013 = module_013::compute_013(x + 13, y + 26);
    let part_014 = module_014::compute_014(x + 14, y + 28);
    let part_015 = module_015::compute_015(x + 15, y + 30);
    let part_016 = module_016::compute_016(x + 16, y + 32);
    let part_017 = module_017::compute_017(x + 17, y + 34);
    let part_018 = module_018::compute_018(x + 18, y + 36);
    let part_019 = module_019::compute_019(x + 19, y + 38);
    (part_000
        + part_001
        + part_002
        + part_003
        + part_004
        + part_005
        + part_006
        + part_007
        + part_008
        + part_009
        + part_010
        + part_011
        + part_012
        + part_013
        + part_014
        + part_015
        + part_016
        + part_017
        + part_018
        + part_019)
        % 100000
}
