// modules - auto-generated by generate_modules.py, do not edit by hand.
// Root of the interconnected module graph.  `run_update` and
// `run_compute` fan out into all submodules, making every function in
// the graph reachable from the DLL's exported entry points.

pub mod module_000;
pub mod module_001;
pub mod module_002;
pub mod module_003;
pub mod module_004;
pub mod module_005;
pub mod module_006;
pub mod module_007;
pub mod module_008;
pub mod module_009;
pub mod module_010;
pub mod module_011;
pub mod module_012;
pub mod module_013;
pub mod module_014;
pub mod module_015;
pub mod module_016;
pub mod module_017;
pub mod module_018;
pub mod module_019;

/// Fan out a game tick into every module and fold the results together.
/// Called by the exported `project_update` in lib.rs.
pub fn run_update(input: i32) -> i32 {
    let part_000 = module_000::tick_000(input + 0);
    let part_001 = module_001::tick_001(input + 1);
    let part_002 = module_002::tick_002(input + 2);
    let part_003 = module_003::tick_003(input + 3);
    let part_004 = module_004::tick_004(input + 4);
    let part_005 = module_005::tick_005(input + 5);
    let part_006 = module_006::tick_006(input + 6);
    let part_007 = module_007::tick_007(input + 7);
    let part_008 = module_008::tick_008(input + 8);
    let part_009 = module_009::tick_009(input + 9);
    let part_010 = module_010::tick_010(input + 10);
    let part_011 = module_011::tick_011(input + 11);
    let part_012 = module_012::tick_012(input + 12);
    let part_013 = module_013::tick_013(input + 13);
    let part_014 = module_014::tick_014(input + 14);
    let part_015 = module_015::tick_015(input + 15);
    let part_016 = module_016::tick_016(input + 16);
    let part_017 = module_017::tick_017(input + 17);
    let part_018 = module_018::tick_018(input + 18);
    let part_019 = module_019::tick_019(input + 19);
    (part_000 + part_001 + part_002 + part_003 + part_004 + part_005 + part_006 + part_007 + part_008 + part_009 + part_010 + part_011 + part_012 + part_013 + part_014 + part_015 + part_016 + part_017 + part_018 + part_019) % 100000
}

/// Fan out a compute request into every module and fold the results.
/// Called by the exported `project_update` in lib.rs.
pub fn run_compute(x: i32, y: i32) -> i32 {
    let part_000 = module_000::compute_000(x + 0, y + 0);
    let part_001 = module_001::compute_001(x + 1, y + 2);
    let part_002 = module_002::compute_002(x + 2, y + 4);
    let part_003 = module_003::compute_003(x + 3, y + 6);
    let part_004 = module_004::compute_004(x + 4, y + 8);
    let part_005 = module_005::compute_005(x + 5, y + 10);
    let part_006 = module_006::compute_006(x + 6, y + 12);
    let part_007 = module_007::compute_007(x + 7, y + 14);
    let part_008 = module_008::compute_008(x + 8, y + 16);
    let part_009 = module_009::compute_009(x + 9, y + 18);
    let part_010 = module_010::compute_010(x + 10, y + 20);
    let part_011 = module_011::compute_011(x + 11, y + 22);
    let part_012 = module_012::compute_012(x + 12, y + 24);
    let part_013 = module_013::compute_013(x + 13, y + 26);
    let part_014 = module_014::compute_014(x + 14, y + 28);
    let part_015 = module_015::compute_015(x + 15, y + 30);
    let part_016 = module_016::compute_016(x + 16, y + 32);
    let part_017 = module_017::compute_017(x + 17, y + 34);
    let part_018 = module_018::compute_018(x + 18, y + 36);
    let part_019 = module_019::compute_019(x + 19, y + 38);
    (part_000 + part_001 + part_002 + part_003 + part_004 + part_005 + part_006 + part_007 + part_008 + part_009 + part_010 + part_011 + part_012 + part_013 + part_014 + part_015 + part_016 + part_017 + part_018 + part_019) % 100000
}

/// Resolve a graph function's address by name.  `pub(crate)` so it is
/// not itself treated as a hot function; reachable from lib.rs.
pub(crate) fn resolve_hot_symbol(name: &str) -> usize {
    match name {
        "run_update" => run_update as usize,
        "run_compute" => run_compute as usize,
        "tick_000" => module_000::tick_000 as usize,
        "compute_000" => module_000::compute_000 as usize,
        "sample_000" => module_000::sample_000 as usize,
        "scale_value_000" => module_000::scale_value_000 as usize,
        "offset_value_000" => module_000::offset_value_000 as usize,
        "tick_001" => module_001::tick_001 as usize,
        "compute_001" => module_001::compute_001 as usize,
        "sample_001" => module_001::sample_001 as usize,
        "scale_value_001" => module_001::scale_value_001 as usize,
        "offset_value_001" => module_001::offset_value_001 as usize,
        "tick_002" => module_002::tick_002 as usize,
        "compute_002" => module_002::compute_002 as usize,
        "sample_002" => module_002::sample_002 as usize,
        "scale_value_002" => module_002::scale_value_002 as usize,
        "offset_value_002" => module_002::offset_value_002 as usize,
        "tick_003" => module_003::tick_003 as usize,
        "compute_003" => module_003::compute_003 as usize,
        "sample_003" => module_003::sample_003 as usize,
        "scale_value_003" => module_003::scale_value_003 as usize,
        "offset_value_003" => module_003::offset_value_003 as usize,
        "tick_004" => module_004::tick_004 as usize,
        "compute_004" => module_004::compute_004 as usize,
        "sample_004" => module_004::sample_004 as usize,
        "scale_value_004" => module_004::scale_value_004 as usize,
        "offset_value_004" => module_004::offset_value_004 as usize,
        "tick_005" => module_005::tick_005 as usize,
        "compute_005" => module_005::compute_005 as usize,
        "sample_005" => module_005::sample_005 as usize,
        "scale_value_005" => module_005::scale_value_005 as usize,
        "offset_value_005" => module_005::offset_value_005 as usize,
        "tick_006" => module_006::tick_006 as usize,
        "compute_006" => module_006::compute_006 as usize,
        "sample_006" => module_006::sample_006 as usize,
        "scale_value_006" => module_006::scale_value_006 as usize,
        "offset_value_006" => module_006::offset_value_006 as usize,
        "tick_007" => module_007::tick_007 as usize,
        "compute_007" => module_007::compute_007 as usize,
        "sample_007" => module_007::sample_007 as usize,
        "scale_value_007" => module_007::scale_value_007 as usize,
        "offset_value_007" => module_007::offset_value_007 as usize,
        "tick_008" => module_008::tick_008 as usize,
        "compute_008" => module_008::compute_008 as usize,
        "sample_008" => module_008::sample_008 as usize,
        "scale_value_008" => module_008::scale_value_008 as usize,
        "offset_value_008" => module_008::offset_value_008 as usize,
        "tick_009" => module_009::tick_009 as usize,
        "compute_009" => module_009::compute_009 as usize,
        "sample_009" => module_009::sample_009 as usize,
        "scale_value_009" => module_009::scale_value_009 as usize,
        "offset_value_009" => module_009::offset_value_009 as usize,
        "tick_010" => module_010::tick_010 as usize,
        "compute_010" => module_010::compute_010 as usize,
        "sample_010" => module_010::sample_010 as usize,
        "scale_value_010" => module_010::scale_value_010 as usize,
        "offset_value_010" => module_010::offset_value_010 as usize,
        "tick_011" => module_011::tick_011 as usize,
        "compute_011" => module_011::compute_011 as usize,
        "sample_011" => module_011::sample_011 as usize,
        "scale_value_011" => module_011::scale_value_011 as usize,
        "offset_value_011" => module_011::offset_value_011 as usize,
        "tick_012" => module_012::tick_012 as usize,
        "compute_012" => module_012::compute_012 as usize,
        "sample_012" => module_012::sample_012 as usize,
        "scale_value_012" => module_012::scale_value_012 as usize,
        "offset_value_012" => module_012::offset_value_012 as usize,
        "tick_013" => module_013::tick_013 as usize,
        "compute_013" => module_013::compute_013 as usize,
        "sample_013" => module_013::sample_013 as usize,
        "scale_value_013" => module_013::scale_value_013 as usize,
        "offset_value_013" => module_013::offset_value_013 as usize,
        "tick_014" => module_014::tick_014 as usize,
        "compute_014" => module_014::compute_014 as usize,
        "sample_014" => module_014::sample_014 as usize,
        "scale_value_014" => module_014::scale_value_014 as usize,
        "offset_value_014" => module_014::offset_value_014 as usize,
        "tick_015" => module_015::tick_015 as usize,
        "compute_015" => module_015::compute_015 as usize,
        "sample_015" => module_015::sample_015 as usize,
        "scale_value_015" => module_015::scale_value_015 as usize,
        "offset_value_015" => module_015::offset_value_015 as usize,
        "tick_016" => module_016::tick_016 as usize,
        "compute_016" => module_016::compute_016 as usize,
        "sample_016" => module_016::sample_016 as usize,
        "scale_value_016" => module_016::scale_value_016 as usize,
        "offset_value_016" => module_016::offset_value_016 as usize,
        "tick_017" => module_017::tick_017 as usize,
        "compute_017" => module_017::compute_017 as usize,
        "sample_017" => module_017::sample_017 as usize,
        "scale_value_017" => module_017::scale_value_017 as usize,
        "offset_value_017" => module_017::offset_value_017 as usize,
        "tick_018" => module_018::tick_018 as usize,
        "compute_018" => module_018::compute_018 as usize,
        "sample_018" => module_018::sample_018 as usize,
        "scale_value_018" => module_018::scale_value_018 as usize,
        "offset_value_018" => module_018::offset_value_018 as usize,
        "tick_019" => module_019::tick_019 as usize,
        "compute_019" => module_019::compute_019 as usize,
        "sample_019" => module_019::sample_019 as usize,
        "scale_value_019" => module_019::scale_value_019 as usize,
        "offset_value_019" => module_019::offset_value_019 as usize,
        _ => 0,
    }
}
