// module_004 - auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_004` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_004(input: i32) -> i32 {
    let local = (input * 7 + 4) % 1000;
    let sample_007 = crate::modules::module_007::sample_007(local + 3);
    let sample_011 = crate::modules::module_011::sample_011(local + 7);
    (local + sample_007 + sample_011) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_004(x: i32, y: i32) -> i32 {
    let base = x * 3 + y * 5;
    let scaled = scale_value_004(base, 11);
    let offset = offset_value_004(base, 13);
    let sample_009 = crate::modules::module_009::sample_009(base + 5);
    let sample_015 = crate::modules::module_015::sample_015(base + 11);
    (base + scaled + offset + sample_009 + sample_015) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only - never
/// recurses into another module - so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_004(seed: i32) -> i32 {
    let local = (seed * 17 + 4) % 100000;
    let scaled = scale_value_004(local, 19);
    let offset = offset_value_004(local, 23);
    (local + scaled + offset) % 100000
}

/// Scales a value and mixes in a per-module constant.  Unique name per module
/// so the host's single `project_resolve_symbol` can find it by name.
pub fn scale_value_004(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 4) % 100000
}

/// Offsets a value and decorates it with string work so the compiler has
/// real (non-trivial) code to emit for this module.  Unique name per module
/// so the host's single `project_resolve_symbol` can find it by name.
pub fn offset_value_004(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 4 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder + 4) % 100000
}
