// module_011 - auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_011` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_011(input: i32) -> i32 {
    let local = (input * 7 + 11) % 1000;
    let sample_014 = crate::modules::module_014::sample_014(local + 3);
    let sample_018 = crate::modules::module_018::sample_018(local + 7);
    (local + sample_014 + sample_018) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_011(x: i32, y: i32) -> i32 {
    let base = x * 3 + y * 5;
    let scaled = scale_value(base, 11);
    let offset = offset_value(base, 13);
    let sample_016 = crate::modules::module_016::sample_016(base + 5);
    let sample_002 = crate::modules::module_002::sample_002(base + 11);
    (base + scaled + offset + sample_016 + sample_002) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only - never
/// recurses into another module - so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_011(seed: i32) -> i32 {
    let local = (seed * 17 + 11) % 100000;
    let scaled = scale_value(local, 19);
    let offset = offset_value(local, 23);
    (local + scaled + offset) % 100000
}

/// Private helper - scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 11) % 100000
}

/// Private helper - offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 11 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder + 11) % 100000
}
