// module_002 - auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_002` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_002(input: i32) -> i32 {
    let local = (input * 7 + 2) % 1000;
    let sample_005 = crate::modules::module_005::sample_005(local + 3);
    let sample_009 = crate::modules::module_009::sample_009(local + 7);
    (local + sample_005 + sample_009) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_002(x: i32, y: i32) -> i32 {
    let base = x * 3 + y * 5;
    let scaled = scale_value_002(base, 11);
    let offset = offset_value_002(base, 13);
    let sample_007 = crate::modules::module_007::sample_007(base + 5);
    let sample_013 = crate::modules::module_013::sample_013(base + 11);
    (base + scaled + offset + sample_007 + sample_013) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only - never
/// recurses into another module - so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_002(seed: i32) -> i32 {
    let local = (seed * 17 + 2) % 100000;
    let scaled = scale_value_002(local, 19);
    let offset = offset_value_002(local, 23);
    (local + scaled + offset) % 100000
}

/// Scales a value and mixes in a per-module constant.  Unique name per module
/// so the host's single `project_resolve_symbol` can find it by name.
pub fn scale_value_002(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 2) % 100000
}

/// Offsets a value and decorates it with string work so the compiler has
/// real (non-trivial) code to emit for this module.  Unique name per module
/// so the host's single `project_resolve_symbol` can find it by name.
pub fn offset_value_002(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 2 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder + 2) % 100000
}
