// module_003 - auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_003` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_003(input: i32) -> i32 {
    let local = (input * 7 + 3) % 1000;
    let sample_006 = crate::modules::module_006::sample_006(local + 3);
    let sample_010 = crate::modules::module_010::sample_010(local + 7);
    (local + sample_006 + sample_010) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_003(x: i32, y: i32) -> i32 {
    let base = x * 3 + y * 5;
    let scaled = scale_value_003(base, 11);
    let offset = offset_value_003(base, 13);
    let sample_008 = crate::modules::module_008::sample_008(base + 5);
    let sample_014 = crate::modules::module_014::sample_014(base + 11);
    (base + scaled + offset + sample_008 + sample_014) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only - never
/// recurses into another module - so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_003(seed: i32) -> i32 {
    let local = (seed * 17 + 3) % 100000;
    let scaled = scale_value_003(local, 19);
    let offset = offset_value_003(local, 23);
    (local + scaled + offset) % 100000
}

/// Scales a value and mixes in a per-module constant.  Unique name per module
/// so the host's single `project_resolve_symbol` can find it by name.
pub fn scale_value_003(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 3) % 100000
}

/// Offsets a value and decorates it with string work so the compiler has
/// real (non-trivial) code to emit for this module.  Unique name per module
/// so the host's single `project_resolve_symbol` can find it by name.
pub fn offset_value_003(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 3 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder + 3) % 100000
}
