// module_015 - auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_015` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_015(input: i32) -> i32 {
    let local = (input * 7 + 15) % 1000;
    let sample_018 = crate::modules::module_018::sample_018(local + 3);
    let sample_002 = crate::modules::module_002::sample_002(local + 7);
    (local + sample_018 + sample_002) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_015(x: i32, y: i32) -> i32 {
    let base = x * 3 + y * 5;
    let scaled = scale_value_015(base, 11);
    let offset = offset_value_015(base, 13);
    let sample_000 = crate::modules::module_000::sample_000(base + 5);
    let sample_006 = crate::modules::module_006::sample_006(base + 11);
    (base + scaled + offset + sample_000 + sample_006) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only - never
/// recurses into another module - so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_015(seed: i32) -> i32 {
    let local = (seed * 17 + 15) % 100000;
    let scaled = scale_value_015(local, 19);
    let offset = offset_value_015(local, 23);
    (local + scaled + offset) % 100000
}

/// Scales a value and mixes in a per-module constant.  Unique name per module
/// so the host's single `project_resolve_symbol` can find it by name.
pub fn scale_value_015(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 15) % 100000
}

/// Offsets a value and decorates it with string work so the compiler has
/// real (non-trivial) code to emit for this module.  Unique name per module
/// so the host's single `project_resolve_symbol` can find it by name.
pub fn offset_value_015(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 15 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder + 15) % 100000
}
