// module_017 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_017` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_017(input: i32) -> i32 {
    let local = (input * 24 + 3) % 1000;
    let sample_020 = crate::modules::module_020::sample_020(local + 3);
    let sample_024 = crate::modules::module_024::sample_024(local + 7);
        (local + sample_020 + sample_024) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_017(x: i32, y: i32) -> i32 {
    let base = x * 20 + y * 22;
    let scaled = scale_value(base, 28);
    let offset = offset_value(base, 30);
    let sample_022 = crate::modules::module_022::sample_022(base + 5);
    let sample_028 = crate::modules::module_028::sample_028(base + 11);
        (base + scaled + offset + sample_022 + sample_028) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_017(seed: i32) -> i32 {
    let local = (seed * 34 + 51) % 100000;
    let scaled = scale_value(local, 36);
    let offset = offset_value(local, 40);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 51) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 017 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
