// module_016 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_016` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_016(input: i32) -> i32 {
    let local = (input * 23 + 3) % 1000;
    let sample_019 = crate::modules::module_019::sample_019(local + 3);
    let sample_023 = crate::modules::module_023::sample_023(local + 7);
        (local + sample_019 + sample_023) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_016(x: i32, y: i32) -> i32 {
    let base = x * 19 + y * 21;
    let scaled = scale_value(base, 27);
    let offset = offset_value(base, 29);
    let sample_021 = crate::modules::module_021::sample_021(base + 5);
    let sample_027 = crate::modules::module_027::sample_027(base + 11);
        (base + scaled + offset + sample_021 + sample_027) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_016(seed: i32) -> i32 {
    let local = (seed * 33 + 48) % 100000;
    let scaled = scale_value(local, 35);
    let offset = offset_value(local, 39);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 48) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 016 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
