// module_006 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_006` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_006(input: i32) -> i32 {
    let local = (input * 13 + 3) % 1000;
    let sample_009 = crate::modules::module_009::sample_009(local + 3);
    let sample_013 = crate::modules::module_013::sample_013(local + 7);
        (local + sample_009 + sample_013) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_006(x: i32, y: i32) -> i32 {
    let base = x * 9 + y * 11;
    let scaled = scale_value(base, 17);
    let offset = offset_value(base, 19);
    let sample_011 = crate::modules::module_011::sample_011(base + 5);
    let sample_017 = crate::modules::module_017::sample_017(base + 11);
        (base + scaled + offset + sample_011 + sample_017) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_006(seed: i32) -> i32 {
    let local = (seed * 23 + 18) % 100000;
    let scaled = scale_value(local, 25);
    let offset = offset_value(local, 29);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 18) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 006 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
