// module_045 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_045` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_045(input: i32) -> i32 {
    let local = (input * 52 + 3) % 1000;
    let sample_048 = crate::modules::module_048::sample_048(local + 3);
    let sample_002 = crate::modules::module_002::sample_002(local + 7);
        (local + sample_048 + sample_002) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_045(x: i32, y: i32) -> i32 {
    let base = x * 48 + y * 50;
    let scaled = scale_value(base, 56);
    let offset = offset_value(base, 58);
    let sample_000 = crate::modules::module_000::sample_000(base + 5);
    let sample_006 = crate::modules::module_006::sample_006(base + 11);
        (base + scaled + offset + sample_000 + sample_006) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_045(seed: i32) -> i32 {
    let local = (seed * 62 + 135) % 100000;
    let scaled = scale_value(local, 64);
    let offset = offset_value(local, 68);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 135) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 045 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
