// module_044 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_044` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_044(input: i32) -> i32 {
    let local = (input * 51 + 3) % 1000;
    let sample_047 = crate::modules::module_047::sample_047(local + 3);
    let sample_001 = crate::modules::module_001::sample_001(local + 7);
        (local + sample_047 + sample_001) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_044(x: i32, y: i32) -> i32 {
    let base = x * 47 + y * 49;
    let scaled = scale_value(base, 55);
    let offset = offset_value(base, 57);
    let sample_049 = crate::modules::module_049::sample_049(base + 5);
    let sample_005 = crate::modules::module_005::sample_005(base + 11);
        (base + scaled + offset + sample_049 + sample_005) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_044(seed: i32) -> i32 {
    let local = (seed * 61 + 132) % 100000;
    let scaled = scale_value(local, 63);
    let offset = offset_value(local, 67);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 132) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 044 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
