// module_022 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_022` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_022(input: i32) -> i32 {
    let local = (input * 29 + 3) % 1000;
    let sample_025 = crate::modules::module_025::sample_025(local + 3);
    let sample_029 = crate::modules::module_029::sample_029(local + 7);
        (local + sample_025 + sample_029) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_022(x: i32, y: i32) -> i32 {
    let base = x * 25 + y * 27;
    let scaled = scale_value(base, 33);
    let offset = offset_value(base, 35);
    let sample_027 = crate::modules::module_027::sample_027(base + 5);
    let sample_033 = crate::modules::module_033::sample_033(base + 11);
        (base + scaled + offset + sample_027 + sample_033) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_022(seed: i32) -> i32 {
    let local = (seed * 39 + 66) % 100000;
    let scaled = scale_value(local, 41);
    let offset = offset_value(local, 45);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 66) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 022 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
