// module_043 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_043` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_043(input: i32) -> i32 {
    let local = (input * 50 + 3) % 1000;
    let sample_046 = crate::modules::module_046::sample_046(local + 3);
    let sample_000 = crate::modules::module_000::sample_000(local + 7);
        (local + sample_046 + sample_000) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_043(x: i32, y: i32) -> i32 {
    let base = x * 46 + y * 48;
    let scaled = scale_value(base, 54);
    let offset = offset_value(base, 56);
    let sample_048 = crate::modules::module_048::sample_048(base + 5);
    let sample_004 = crate::modules::module_004::sample_004(base + 11);
        (base + scaled + offset + sample_048 + sample_004) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_043(seed: i32) -> i32 {
    let local = (seed * 60 + 129) % 100000;
    let scaled = scale_value(local, 62);
    let offset = offset_value(local, 66);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 129) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 043 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
