// module_004 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_004` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_004(input: i32) -> i32 {
    let local = (input * 11 + 3) % 1000;
    let sample_007 = crate::modules::module_007::sample_007(local + 3);
    let sample_011 = crate::modules::module_011::sample_011(local + 7);
        (local + sample_007 + sample_011) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_004(x: i32, y: i32) -> i32 {
    let base = x * 7 + y * 9;
    let scaled = scale_value(base, 15);
    let offset = offset_value(base, 17);
    let sample_009 = crate::modules::module_009::sample_009(base + 5);
    let sample_015 = crate::modules::module_015::sample_015(base + 11);
        (base + scaled + offset + sample_009 + sample_015) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_004(seed: i32) -> i32 {
    let local = (seed * 21 + 12) % 100000;
    let scaled = scale_value(local, 23);
    let offset = offset_value(local, 27);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 12) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 004 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
