// module_021 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_021` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_021(input: i32) -> i32 {
    let local = (input * 28 + 3) % 1000;
    let sample_024 = crate::modules::module_024::sample_024(local + 3);
    let sample_028 = crate::modules::module_028::sample_028(local + 7);
        (local + sample_024 + sample_028) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_021(x: i32, y: i32) -> i32 {
    let base = x * 24 + y * 26;
    let scaled = scale_value(base, 32);
    let offset = offset_value(base, 34);
    let sample_026 = crate::modules::module_026::sample_026(base + 5);
    let sample_032 = crate::modules::module_032::sample_032(base + 11);
        (base + scaled + offset + sample_026 + sample_032) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_021(seed: i32) -> i32 {
    let local = (seed * 38 + 63) % 100000;
    let scaled = scale_value(local, 40);
    let offset = offset_value(local, 44);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 63) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 021 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
