// module_027 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_027` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_027(input: i32) -> i32 {
    let local = (input * 34 + 3) % 1000;
    let sample_030 = crate::modules::module_030::sample_030(local + 3);
    let sample_034 = crate::modules::module_034::sample_034(local + 7);
        (local + sample_030 + sample_034) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_027(x: i32, y: i32) -> i32 {
    let base = x * 30 + y * 32;
    let scaled = scale_value(base, 38);
    let offset = offset_value(base, 40);
    let sample_032 = crate::modules::module_032::sample_032(base + 5);
    let sample_038 = crate::modules::module_038::sample_038(base + 11);
        (base + scaled + offset + sample_032 + sample_038) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_027(seed: i32) -> i32 {
    let local = (seed * 44 + 81) % 100000;
    let scaled = scale_value(local, 46);
    let offset = offset_value(local, 50);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 81) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 027 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
