// module_034 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_034` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_034(input: i32) -> i32 {
    let local = (input * 41 + 3) % 1000;
    let sample_037 = crate::modules::module_037::sample_037(local + 3);
    let sample_041 = crate::modules::module_041::sample_041(local + 7);
        (local + sample_037 + sample_041) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_034(x: i32, y: i32) -> i32 {
    let base = x * 37 + y * 39;
    let scaled = scale_value(base, 45);
    let offset = offset_value(base, 47);
    let sample_039 = crate::modules::module_039::sample_039(base + 5);
    let sample_045 = crate::modules::module_045::sample_045(base + 11);
        (base + scaled + offset + sample_039 + sample_045) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_034(seed: i32) -> i32 {
    let local = (seed * 51 + 102) % 100000;
    let scaled = scale_value(local, 53);
    let offset = offset_value(local, 57);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 102) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 034 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
