// module_015 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_015` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_015(input: i32) -> i32 {
    let local = (input * 22 + 3) % 1000;
    let sample_018 = crate::modules::module_018::sample_018(local + 3);
    let sample_022 = crate::modules::module_022::sample_022(local + 7);
        (local + sample_018 + sample_022) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_015(x: i32, y: i32) -> i32 {
    let base = x * 18 + y * 20;
    let scaled = scale_value(base, 26);
    let offset = offset_value(base, 28);
    let sample_020 = crate::modules::module_020::sample_020(base + 5);
    let sample_026 = crate::modules::module_026::sample_026(base + 11);
        (base + scaled + offset + sample_020 + sample_026) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_015(seed: i32) -> i32 {
    let local = (seed * 32 + 45) % 100000;
    let scaled = scale_value(local, 34);
    let offset = offset_value(local, 38);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 45) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 015 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
