// module_005 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_005` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_005(input: i32) -> i32 {
    let local = (input * 12 + 3) % 1000;
    let sample_008 = crate::modules::module_008::sample_008(local + 3);
    let sample_012 = crate::modules::module_012::sample_012(local + 7);
        (local + sample_008 + sample_012) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_005(x: i32, y: i32) -> i32 {
    let base = x * 8 + y * 10;
    let scaled = scale_value(base, 16);
    let offset = offset_value(base, 18);
    let sample_010 = crate::modules::module_010::sample_010(base + 5);
    let sample_016 = crate::modules::module_016::sample_016(base + 11);
        (base + scaled + offset + sample_010 + sample_016) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_005(seed: i32) -> i32 {
    let local = (seed * 22 + 15) % 100000;
    let scaled = scale_value(local, 24);
    let offset = offset_value(local, 28);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 15) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 005 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
