// module_010 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_010` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_010(input: i32) -> i32 {
    let local = (input * 17 + 3) % 1000;
    let sample_013 = crate::modules::module_013::sample_013(local + 3);
    let sample_017 = crate::modules::module_017::sample_017(local + 7);
        (local + sample_013 + sample_017) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_010(x: i32, y: i32) -> i32 {
    let base = x * 13 + y * 15;
    let scaled = scale_value(base, 21);
    let offset = offset_value(base, 23);
    let sample_015 = crate::modules::module_015::sample_015(base + 5);
    let sample_021 = crate::modules::module_021::sample_021(base + 11);
        (base + scaled + offset + sample_015 + sample_021) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_010(seed: i32) -> i32 {
    let local = (seed * 27 + 30) % 100000;
    let scaled = scale_value(local, 29);
    let offset = offset_value(local, 33);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 30) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 010 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
