// module_031 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_031` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_031(input: i32) -> i32 {
    let local = (input * 38 + 3) % 1000;
    let sample_034 = crate::modules::module_034::sample_034(local + 3);
    let sample_038 = crate::modules::module_038::sample_038(local + 7);
        (local + sample_034 + sample_038) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_031(x: i32, y: i32) -> i32 {
    let base = x * 34 + y * 36;
    let scaled = scale_value(base, 42);
    let offset = offset_value(base, 44);
    let sample_036 = crate::modules::module_036::sample_036(base + 5);
    let sample_042 = crate::modules::module_042::sample_042(base + 11);
        (base + scaled + offset + sample_036 + sample_042) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_031(seed: i32) -> i32 {
    let local = (seed * 48 + 93) % 100000;
    let scaled = scale_value(local, 50);
    let offset = offset_value(local, 54);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 93) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 031 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
