// module_020 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_020` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_020(input: i32) -> i32 {
    let local = (input * 27 + 3) % 1000;
    let sample_023 = crate::modules::module_023::sample_023(local + 3);
    let sample_027 = crate::modules::module_027::sample_027(local + 7);
        (local + sample_023 + sample_027) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_020(x: i32, y: i32) -> i32 {
    let base = x * 23 + y * 25;
    let scaled = scale_value(base, 31);
    let offset = offset_value(base, 33);
    let sample_025 = crate::modules::module_025::sample_025(base + 5);
    let sample_031 = crate::modules::module_031::sample_031(base + 11);
        (base + scaled + offset + sample_025 + sample_031) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_020(seed: i32) -> i32 {
    let local = (seed * 37 + 60) % 100000;
    let scaled = scale_value(local, 39);
    let offset = offset_value(local, 43);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 60) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 020 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
