// module_049 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_049` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_049(input: i32) -> i32 {
    let local = (input * 56 + 3) % 1000;
    let sample_002 = crate::modules::module_002::sample_002(local + 3);
    let sample_006 = crate::modules::module_006::sample_006(local + 7);
        (local + sample_002 + sample_006) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_049(x: i32, y: i32) -> i32 {
    let base = x * 52 + y * 54;
    let scaled = scale_value(base, 60);
    let offset = offset_value(base, 62);
    let sample_004 = crate::modules::module_004::sample_004(base + 5);
    let sample_010 = crate::modules::module_010::sample_010(base + 11);
        (base + scaled + offset + sample_004 + sample_010) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_049(seed: i32) -> i32 {
    let local = (seed * 66 + 147) % 100000;
    let scaled = scale_value(local, 68);
    let offset = offset_value(local, 72);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 147) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 049 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
