// module_042 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_042` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_042(input: i32) -> i32 {
    let local = (input * 49 + 3) % 1000;
    let sample_045 = crate::modules::module_045::sample_045(local + 3);
    let sample_049 = crate::modules::module_049::sample_049(local + 7);
        (local + sample_045 + sample_049) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_042(x: i32, y: i32) -> i32 {
    let base = x * 45 + y * 47;
    let scaled = scale_value(base, 53);
    let offset = offset_value(base, 55);
    let sample_047 = crate::modules::module_047::sample_047(base + 5);
    let sample_003 = crate::modules::module_003::sample_003(base + 11);
        (base + scaled + offset + sample_047 + sample_003) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_042(seed: i32) -> i32 {
    let local = (seed * 59 + 126) % 100000;
    let scaled = scale_value(local, 61);
    let offset = offset_value(local, 65);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 126) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 042 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
