// module_024 — auto-generated by generate_modules.py, do not edit by hand.
// Part of an interconnected module graph: this module is called by the root
// fan-out AND its `sample_024` leaf is pulled by other modules.

/// Main tick entry point for this module.  Computes a local value from the
/// input frame and folds in values pulled from other modules' leaf functions.
pub fn tick_024(input: i32) -> i32 {
    let local = (input * 31 + 3) % 1000;
    let sample_027 = crate::modules::module_027::sample_027(local + 3);
    let sample_031 = crate::modules::module_031::sample_031(local + 7);
        (local + sample_027 + sample_031) % 100000
}

/// Main compute entry point for this module.  Takes x/y, scales them, then
/// folds in values pulled from other modules' leaf functions.
pub fn compute_024(x: i32, y: i32) -> i32 {
    let base = x * 27 + y * 29;
    let scaled = scale_value(base, 35);
    let offset = offset_value(base, 37);
    let sample_029 = crate::modules::module_029::sample_029(base + 5);
    let sample_035 = crate::modules::module_035::sample_035(base + 11);
        (base + scaled + offset + sample_029 + sample_035) % 100000
}

/// Leaf function called by OTHER modules.  Does local work only — never
/// recurses into another module — so the runtime stays linear even though
/// every module references this symbol.
pub fn sample_024(seed: i32) -> i32 {
    let local = (seed * 41 + 72) % 100000;
    let scaled = scale_value(local, 43);
    let offset = offset_value(local, 47);
    (local + scaled + offset) % 100000
}

/// Private helper — scales a value and mixes in a per-module constant.
fn scale_value(value: i32, multiplier: i32) -> i32 {
    (value * multiplier + 72) % 100000
}

/// Private helper — offsets a value and decorates it with string work so the
/// compiler has real (non-trivial) code to emit for this module.
fn offset_value(value: i32, adder: i32) -> i32 {
    let decorated = format!("module 024 value: {}", value + adder);
    let uppercase = decorated.to_uppercase();
    let length = uppercase.len() as i32;
    (length + value + adder) % 100000
}
