# REQUIREMENTS
#   Python 3.  No third-party dependencies (stdlib only).
#
# DESCRIPTION
#   Generates `project/src/bloat_gen_no_export.rs` for the mini-engine's
#   `project` crate: thousands of `pub(crate) fn bloat_N() -> i32` functions.
#   They are dead code from the DLL's export table point of view (never
#   exported, never called by the hot path), so they add pure volume: the
#   front-end, type-check, codegen and link all have to process every one of
#   them on a full `cargo build`, but the leaf patch (which only compiles
#   `project_update` standalone) never sees them.
#
#   Following the live-coding research lesson, these use `String::from("x")`
#   instead of `format!` so the macro-expansion cost stays near zero while the
#   per-function code volume stays high.  A small arithmetic loop gives the
#   optimizer and codegen real (non-trivial) work per function.
#
# USAGE
#   python gen_bloat.py
#       Generates project/src/bloat_gen_no_export.rs with 2000 functions.
#
#   python gen_bloat.py --count 5000
#       Generates 5000 functions instead of 2000.
#
#   python gen_bloat.py --dry-run
#       Print how many functions would be written without writing anything.
#
# EXAMPLE USAGE
#   python gen_bloat.py --dry-run
#   python gen_bloat.py
#
# --- SCRIPT ---

import argparse
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Defaults - matches the live_coding_mini_engine layout.
# ---------------------------------------------------------------------------

BLOAT_COUNT_DEFAULT = 2000
OUTPUT_FILE = Path("project") / "src" / "bloat_gen_no_export.rs"


def build_bloat_function(function_index: int) -> str:
    """Return one bloat function body (even/odd variants like the classic)."""
    index_str = f"{function_index:04d}"
    if function_index % 2 == 0:
        tail = "    (_len + _extra.len()) as i32"
    else:
        tail = "    (_len + _extra.len() + 1) as i32"
    return f"""pub(crate) fn bloat_{index_str}() -> i32 {{
    let _name = String::from("x");
    let _greeting = String::from("x");
    let _upper = _greeting.to_uppercase();
    let _len = _upper.len();
    let _extra = String::from("x");
    let mut accumulator = {tail};
    for step in 0..16 {{
        accumulator = accumulator.wrapping_mul(31).wrapping_add(step + {function_index % 7});
    }}
    accumulator
}}
"""


def build_bloat_file(function_count: int) -> str:
    """Return the full bloat file contents."""
    header = (
        "// auto-generated by gen_bloat.py - do not edit by hand\n"
        f"// {function_count} unique functions with String work (no format!, per the live-coding lesson)\n"
        "#![allow(dead_code, unused_variables)]\n\n"
    )
    body = "\n".join(build_bloat_function(index) for index in range(function_count))
    return header + body + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the bloat file for the mini engine's project crate.")
    parser.add_argument("--count", type=int, default=BLOAT_COUNT_DEFAULT, help=f"number of bloat functions (default {BLOAT_COUNT_DEFAULT})")
    parser.add_argument("--dry-run", action="store_true", help="print what would be written without writing")
    args = parser.parse_args()

    if args.count < 1:
        print(f"error: --count must be >= 1, got {args.count}", file=sys.stderr)
        return 1

    content = build_bloat_file(args.count)

    if args.dry_run:
        print(f"would write {OUTPUT_FILE} with {args.count} functions ({len(content)} bytes)")
        return 0

    OUTPUT_FILE.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT_FILE} ({args.count} functions, {len(content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
